# render.yaml
# プロジェクトのルートディレクトリに配置します (例: my-chat-app/render.yaml)

services:
  # --- 1. PostgreSQL データベースサービス ---
  - type: pserv
    name: chat-db
    plan: free # または starter, standard
    # databaseName: my_chat_database # オプション: データベース名を指定
    # region: oregon # オプション: リージョンを指定 (例: oregon, frankfurt, singapore)

  # --- 2. FastAPI バックエンドサービス ---
  - type: web
    name: chat-backend
    env: python
    region: oregon # データベースと同じリージョンを推奨
    rootDir: backend # FastAPIコードがあるディレクトリ
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /docs # または /redoc, または / （FastAPIのエンドポイント）
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chat-db # 上で定義したデータベースの名前を参照
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Renderが自動的に安全なキーを生成
        # または value: your-super-secret-key-for-jwt # 手動で設定する場合

  # --- 3. React フロントエンドサービス ---
  - type: static
    name: chat-frontend
    region: oregon # バックエンドと同じリージョンを推奨
    rootDir: frontend # Reactコードがあるディレクトリ
    buildCommand: npm install && npm run build
    publishPath: build # Reactのビルド出力ディレクトリ
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: chat-backend # 上で定義したバックエンドの名前を参照
          property: url
